name: release-please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            # Required for pushing to the repository
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: pnpm install

            - name: Build jsrepo-manifest.json
              run: pnpm build

            - name: Format manifest
              run: pnpm format

            - name: Create pull request with changes
              uses: peter-evans/create-pull-request@v7
              with:
                  title: "chore: update `jsrepo-manifest.json`"
                  body: |
                      - Update `jsrepo-manifest.json`

                      ---
                      This PR was auto generated
                  assignees: ieedan
                  branch: build-manifest
                  commit-message: build `jsrepo-manifest.json`

    release-please:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
