name: release-please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          # Required for pushing to the repository
          contents: write
          pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: pnpm install

            - name: Build blocks-manifest.json
              run: pnpm build
            
            - name: Commit to main
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add .
                git commit -m "chore: Update blocks-manifest.json" || exit 0
                git push origin main

    release-please:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
